import {
  ProjectMetadata,
  Track,
  SessionPlayerPersona,
  SMIRIntent,
  ChangeSet,
  RevisionNode,
  CapabilityEntry,
  PipelineStage,
  SongSection,
} from '../types/soulsonus';

export const INITIAL_METADATA: ProjectMetadata = {
  id: 'proj_untitled_soul_01',
  name: 'Untitled Soul',
  revision: 28,
  bpm: 110,
  key: 'C MIN',
  timeSignature: '4/4',
  timecode: '01:02:14',
  storageUsed: '2.4 GB',
  storageTotal: '50 GB',
  sampleRate: '48.0 kHz',
  bitDepth: '24-bit Floating Point',
  seedSignature: 'ss_c09e8841a3d9f7832be041c2e409',
  rightsStatus: 'TRACKED · 100% Creator Origin Lineage',
  creatorOriginPct: 82,
  collaborators: ['Devon Cole (Owner)', 'Marcus Miller AI', 'Atmosphere Cloud'],
};

export const INITIAL_SONG_SECTIONS: SongSection[] = [
  { id: 'sec_intro', name: 'INTRO', startBar: 1, endBar: 4, color: '#334155' },
  { id: 'sec_v1', name: 'VERSE 1', startBar: 5, endBar: 12, color: '#f59e0b', lyrics: [
    'Walking through the shadows of the late night',
    'Listening for a whisper in the cold',
    'Every step I take is searching for the light',
    'Holding on to memories of gold'
  ]},
  { id: 'sec_chorus', name: 'CHORUS', startBar: 13, endBar: 20, color: '#06b6d4', lyrics: [
    'Hold on till the morning light',
    'We made it through the hardest fight',
    'Lift your head up to the sky',
    'Never gonna let this feeling die'
  ]},
  { id: 'sec_v2', name: 'VERSE 2', startBar: 21, endBar: 28, color: '#334155' },
  { id: 'sec_bridge', name: 'BRIDGE', startBar: 29, endBar: 36, color: '#a855f7' },
  { id: 'sec_final', name: 'FINAL CHORUS', startBar: 37, endBar: 48, color: '#ec4899' },
];

export const INITIAL_TRACKS: Track[] = [
  {
    id: 't1',
    number: '01',
    name: 'KICK',
    type: 'Audio',
    subtitle: 'Drums · Audio',
    armed: false,
    muted: false,
    soloed: false,
    volume: 0.85,
    pan: 0,
    color: '#06b6d4',
    bus: 'Drums Bus',
    plugins: ['Tape Saturator', 'Solid State EQ'],
    activeTake: 1,
    availableTakes: [1, 2],
    clips: [
      {
        id: 'c1',
        name: 'Original Drum Performance',
        startBar: 1,
        lengthBars: 4,
        takeNumber: 1,
        color: '#0e7490',
        waveformPoints: [0.3, 0.9, 0.1, 0.4, 0.8, 0.1, 0.5, 0.9, 0.2, 0.3, 0.7, 0.1],
        isCreatorOrigin: true,
      },
    ],
  },
  {
    id: 't2',
    number: '02',
    name: 'KEYS',
    type: 'MIDI',
    subtitle: 'MIDI · Instrument',
    armed: false,
    muted: false,
    soloed: false,
    volume: 0.78,
    pan: -0.2,
    color: '#10b981',
    bus: 'Music Bus',
    plugins: ['Rhodes MK-I', 'Velvet Chorus'],
    activeTake: 2,
    availableTakes: [1, 2, 3],
    clips: [
      {
        id: 'c2',
        name: 'Keys · Take 2',
        startBar: 2,
        lengthBars: 5,
        takeNumber: 2,
        color: '#047857',
        notesSummary: 'Cm9 — Fm9 — Gm7 voicing',
      },
    ],
  },
  {
    id: 't3',
    number: '03',
    name: 'LEAD VOCAL',
    type: 'Audio',
    subtitle: 'ARMED · Creator Origin',
    armed: true,
    muted: false,
    soloed: false,
    volume: 0.92,
    pan: 0,
    color: '#a855f7',
    bus: 'Vocal Bus',
    plugins: ['SoulVocal Preamp', 'Opto Tube Compressor', 'Chamber Space'],
    activeTake: 1,
    availableTakes: [1, 2, 3],
    clips: [
      {
        id: 'c3',
        name: 'Lead Vocal · Take 1',
        startBar: 1.5,
        lengthBars: 4,
        takeNumber: 1,
        color: '#7e22ce',
        isCreatorOrigin: true,
        smirId: 'smir_lead_01',
        waveformPoints: [0.1, 0.4, 0.7, 0.85, 0.9, 0.6, 0.7, 0.8, 0.4, 0.2, 0.5, 0.8],
      },
    ],
  },
  {
    id: 't4',
    number: '04',
    name: 'MARCUS BASS',
    type: 'Session Player',
    subtitle: 'Session Player · Take 3',
    armed: false,
    muted: false,
    soloed: false,
    volume: 0.82,
    pan: 0,
    color: '#0284c7',
    bus: 'Bass Bus',
    plugins: ['Marcus Preamp DI', 'Tube Leveler'],
    activeTake: 3,
    availableTakes: [1, 2, 3],
    clips: [
      {
        id: 'c4',
        name: 'Marcus · Bass · Take 3',
        startBar: 2.5,
        lengthBars: 5,
        takeNumber: 3,
        color: '#0369a1',
        notesSummary: 'Church pocket, chromatic walks, locks with Jay kick',
      },
    ],
  },
  {
    id: 't5',
    number: '05',
    name: 'BGV SECTION',
    type: 'Group Bus',
    subtitle: 'S/A/T · Group Bus',
    armed: false,
    muted: false,
    soloed: false,
    volume: 0.75,
    pan: 0.25,
    color: '#9333ea',
    bus: 'Vocal Bus',
    plugins: ['Vocal Doubler', 'Lush Plate Reverb'],
    activeTake: 1,
    availableTakes: [1, 2],
    clips: [
      {
        id: 'c5',
        name: 'Final Chorus · Harmony',
        startBar: 5,
        lengthBars: 4,
        takeNumber: 1,
        color: '#6b21a8',
        notesSummary: '3-part tight gospel harmony following lead phrase',
      },
    ],
  },
];

export const INITIAL_SESSION_PLAYERS: SessionPlayerPersona[] = [
  {
    id: 'player_marcus',
    name: 'MARCUS',
    role: 'BASS',
    tags: ['Gospel', 'Soul', 'Neo-Soul'],
    status: 'LISTENING READY',
    instrument: 'Fender Jazz Bass 1974 (Flatwounds)',
    bio: 'Detroit-bred pocket bassist. Leans heavy into church groove, subtle chromatic walking lines, dynamic thumb accents and conscious pocket placement.',
    allowedVariations: 'Permitted: harmonic turnaround fills, syncopated ghost notes. Prohibited: clashing in lead vocal 200-500Hz lane.',
    rules: [
      'Locks primarily to Jay’s Kick drum transient',
      'Ducks under lead vocal phrase peaks',
      'Follows C Minor harmonic contours with sharp 9 turnaround options'
    ],
    activeTake: 3,
    takes: [
      { id: 1, title: 'Take 1 · Strict Pocket', description: 'Understated root notes, fundamental weight, 0% fills.', grooveVibe: 'Deep Pocket', harmonicFlavor: 'Root-Fifth', clipId: 'c_m1' },
      { id: 2, title: 'Take 2 · Melodic Neo-Soul', description: 'Upper-register slides, thumb pops on beat 4, walking turnaround.', grooveVibe: 'Loose Neo-Soul', harmonicFlavor: 'Dorian extensions', clipId: 'c_m2' },
      { id: 3, title: 'Take 3 · SoulSonus Comped', description: 'Locks with kick in verse, opens up harmonic color into chorus turnaround.', grooveVibe: 'Live Dynamic Gospel', harmonicFlavor: 'Dynamic Extensions', clipId: 'c_m3' },
    ],
  },
  {
    id: 'player_jay',
    name: 'JAY',
    role: 'DRUMS',
    tags: ['Pocket', 'Live', 'Dynamic'],
    status: 'SESSION READY',
    instrument: 'Custom Birch Kit w/ Vintage Zildjian K Cymbals',
    bio: 'Dynamic pocket drummer combining acoustic gospel kit dynamics with modern punch. Natural humanization swing (+8ms laid-back on 2 and 4).',
    allowedVariations: 'Permitted: ghost snares, hi-hat shoulder accents. Prohibited: tempo drifting.',
    rules: [
      'Keep snare backbeat grounded',
      'Humanize velocity dynamics between 65 and 115'
    ],
    activeTake: 1,
    takes: [
      { id: 1, title: 'Take 1 · Live Gospel Pocket', description: 'Full kit performance, warm room mics, dynamic ghost notes.', grooveVibe: 'Humanized Live Pocket', harmonicFlavor: 'Acoustic', clipId: 'c_j1' },
    ],
  },
  {
    id: 'player_elena',
    name: 'ELENA',
    role: 'KEYS',
    tags: ['Gospel', 'R&B', 'Piano'],
    status: 'SESSION READY',
    instrument: 'Fender Rhodes Stage 73 + Yamaha C7 Grand',
    bio: 'Julliard & Atlanta gospel church pianist. Expert in lush 9th/11th/13th chord voicings, gospel turnarounds, and gentle polyrhythmic comping.',
    allowedVariations: 'Permitted: chord reharmonization during vocal pauses. Prohibited: muddy bass octave clashes with Marcus.',
    rules: [
      'High-pass left hand below 180Hz to leave room for Marcus',
      'Compliment vocal emotional trajectory'
    ],
    activeTake: 2,
    takes: [
      { id: 1, title: 'Take 1 · Acoustic Grand', description: 'Warm grand piano voicings, gentle ballad comping.', grooveVibe: 'Stately Acoustic', harmonicFlavor: 'Pure minor', clipId: 'c_e1' },
      { id: 2, title: 'Take 2 · Rhodes Stage 73', description: 'Belly tremolo, lush neo-soul clusters, gentle chorus sheen.', grooveVibe: 'Warm Tremolo Pocket', harmonicFlavor: 'Cm9 / Fm9 clusters', clipId: 'c_e2' },
    ],
  },
  {
    id: 'player_bgv',
    name: 'BGV SECTION',
    role: 'VOCALS',
    tags: ['Soprano', 'Alto', 'Tenor'],
    status: 'HARMONY READY',
    instrument: '3-Part Vocal Ensemble (SAT)',
    bio: 'Harmonically agile vocal trio trained in gospel and modern soul harmonies. Features intelligent formants, breath dynamics, and precise blend.',
    allowedVariations: 'Permitted: open 3rds, 5ths, flat 7ths on sustained vowels.',
    rules: [
      'Track lead vocal pitch contour tightly',
      'Auto-duck attack transients behind lead consonant delivery'
    ],
    activeTake: 1,
    takes: [
      { id: 1, title: 'Take 1 · Chorus Harmony Trio', description: 'Soprano on 3rd, Alto on unison/5th, Tenor on warm 7th base.', grooveVibe: 'Tight Gospel Blend', harmonicFlavor: 'Open Triad Harmony', clipId: 'c_b1' },
    ],
  },
];

export const INITIAL_SMIR_INTENT: SMIRIntent = {
  id: 'smir_lead_01',
  trackId: 't3',
  title: 'Lead Hook Phrase',
  phrase: "Hold on till the morning light",
  source: 'Creator Performance • Preserved',
  intendedRole: 'Lead Vocal Anchor & Emotional Axis',
  contourData: [0.2, 0.45, 0.6, 0.85, 0.7, 0.5, 0.9, 0.65, 0.3],
  grooveDelta: '+12ms late pocket (laid back feeling)',
  emotionalDirection: 'Tender vulnerability blooming into grounded resolve',
  preservationRequirements: [
    'Preserve creator micro-pitch inflections and vocal husk',
    'Retain syllabic timing: never quantize consonants',
    'Maintain dry creator audio untouched on Track 03',
    'Derivations must preserve creator SeedSignature origin'
  ],
  currentRealization: 'Original Audio Recording (Dry) -> SoulVocal Preamp -> Sent to BGV Generator',
  providerUsed: 'Native Creator Origin (0% synthetic drift)',
};

export const INITIAL_CHANGESETS: ChangeSet[] = [
  {
    id: 'cs_28',
    timestamp: 'Just now',
    naturalPrompt: 'Marcus, stay out of the vocal.',
    targetScope: 'Track 04 · Marcus Bass (Bars 13-20 Chorus)',
    status: 'PROPOSED',
    preservedElements: [
      'Kick drum alignment with Jay',
      'Harmonic root movement (C -> Eb -> F -> G)',
      'Creator rhythm pocket (+12ms swing)'
    ],
    permittedChanges: [
      'Low-pass filter slope on upper harmonics during vocal lines (250Hz - 600Hz)',
      'Duck upper fretboard melodic fills into verse turnaround only'
    ],
    prohibitedChanges: [
      'Changing bass groove tempo or tempo curve',
      'Modifying original creator vocal track or drum pattern',
      'Replacing Marcus persona with generic bass model'
    ],
    impactSummary: 'Creates 3.2 dB of acoustic breathing room for creator lead vocal while maintaining church pocket.',
    affectedTracks: ['t4'],
    createdRevision: 29,
  },
  {
    id: 'cs_27',
    timestamp: '14 min ago',
    naturalPrompt: 'Warm my lead vocal.',
    targetScope: 'Track 03 · Lead Vocal (Preamp & Insert Chain)',
    status: 'APPLIED',
    preservedElements: ['Original audio clip bytes', 'Pitch contour', 'Micro-timing'],
    permittedChanges: ['Saturation curve (2nd order harmonic generation)', 'Tube leveling ratio 2:1'],
    prohibitedChanges: ['Pitch correction or autotune alteration', 'Phonetic alteration'],
    impactSummary: 'Applied 1.8dB analog warmth across 1.5kHz shelf without touching source clip audio.',
    affectedTracks: ['t3'],
    createdRevision: 28,
  },
  {
    id: 'cs_26',
    timestamp: '1 hour ago',
    naturalPrompt: 'Bring the backgrounds in on the second chorus.',
    targetScope: 'Track 05 · BGV Section (Bars 37-48)',
    status: 'APPLIED',
    preservedElements: ['Lead vocal volume and priority', 'Jay drum mix'],
    permittedChanges: ['BGV clip placement on Final Chorus', 'Stereo spread +40%'],
    prohibitedChanges: ['BGV masking lead vocal words'],
    impactSummary: 'Harmonized 3-part vocal arrangement on Bars 37-48.',
    affectedTracks: ['t5'],
    createdRevision: 27,
  },
];

export const INITIAL_REVISIONS: RevisionNode[] = [
  { id: 'rev_28', revision: 28, label: 'Current Session · Armed Lead Vocal', timestamp: 'Today 14:02', author: 'Devon Cole', notes: 'Lead Vocal Take 1 recorded, Marcus Take 3 comped', isCurrent: true },
  { id: 'rev_27', revision: 27, label: 'Warm Vocal Insert Applied', timestamp: 'Today 13:48', author: 'Studio Intelligence', notes: 'Tube warmth on Lead Vocal without source alteration' },
  { id: 'rev_26', revision: 26, label: 'BGV Section Final Chorus Arranged', timestamp: 'Today 13:00', author: 'Devon Cole + Elena', notes: '3-part harmony arrangement locked' },
  { id: 'rev_25', revision: 25, label: 'Marcus Take 1/2/3 Session Recording', timestamp: 'Yesterday 18:22', author: 'Marcus Miller AI', notes: 'Generated 3 stylistic bass takes for evaluation' },
  { id: 'rev_24', revision: 24, label: 'Initial Project Tracking with Jay', timestamp: 'Yesterday 16:10', author: 'Devon Cole', notes: 'Acoustic drum capture imported & quantized' },
];

export const INITIAL_CAPABILITIES: CapabilityEntry[] = [
  {
    id: 'cap_pitch_hum',
    capability: 'Hum / Pitch to Notes (audio.melody.extract)',
    category: 'Analysis & SMIR Extraction',
    description: 'Detects polyphonic/monophonic note onsets, F0 contour, and converts voice hum into MIDI notes.',
    currentProvider: 'Basic Pitch (Spotify)',
    availableProviders: ['Basic Pitch (Spotify)', 'CREPE Neural F0', 'SoulSonus Pitch Core'],
    codeLicense: 'Apache-2.0',
    checkpointLicense: 'Apache-2.0',
    commercialStatus: 'COMMERCIAL_OK',
    modelHash: 'sha256_bp98f3a0112c',
    soulsonusLogic: 'Interprets creator intent, maps to target instrument/voice profile, preserves micro-pitch nuances.',
    ossEngine: 'Basic Pitch CNN note event detector + CREPE continuous pitch contour',
    adapterContract: 'AudioBuffer (48kHz Mono) -> NoteEvents[] (pitch, onset, offset, velocity, contourVector)',
    latencyMs: 14,
    status: 'ACTIVE',
  },
  {
    id: 'cap_rhythm_groove',
    capability: 'Beat & Transient Tracking (rhythm.timing.extract)',
    category: 'Groove Intelligence',
    description: 'Extracts creator beatbox onsets, micro-timing (+12ms swing), and rhythm profile grid.',
    currentProvider: 'SoulSonus Beatbox Classifier + BeatNet',
    availableProviders: ['SoulSonus Beatbox Classifier + BeatNet', 'Beat This (Offline)', 'Deepbox Ref'],
    codeLicense: 'Apache-2.0 (BeatNet)',
    checkpointLicense: 'Apache-2.0',
    commercialStatus: 'COMMERCIAL_OK',
    modelHash: 'sha256_bn44c82b09',
    soulsonusLogic: 'Translates mouth sounds into Drum Kit instruments, retains human swing without rigid quantization.',
    ossEngine: 'BeatNet particle filter DBN + SoulSonus transient classifier',
    adapterContract: 'AudioBuffer -> TransientEvent[] { type: kick|snare|hat, offsetMs, confidence }',
    latencyMs: 18,
    status: 'ACTIVE',
  },
  {
    id: 'cap_ace_generate',
    capability: 'realization.music.generate (ACE text2music)',
    category: 'ACE-Step 1.5 XL Base',
    description: 'Synthesizes bounded music sections from musical description text and section constraints.',
    currentProvider: 'ACE-Step 1.5 XL Base (text2music)',
    availableProviders: ['ACE-Step 1.5 XL Base (text2music)', 'SoulNative Direct Synth'],
    codeLicense: 'Apache-2.0',
    checkpointLicense: 'OpenRAIL-M / Permissive',
    commercialStatus: 'COMMERCIAL_OK',
    modelHash: 'sha256_ace15_xl_base_09bf',
    soulsonusLogic: 'SoulSonus owns musical plan, key/BPM lock, and ChangeSet preservation contract.',
    ossEngine: 'ACE-Step 1.5 Diffusion Backbone',
    adapterContract: 'TextPrompt + SMIRConstraints + Bars -> AudioBuffer (Exact bar boundary match)',
    latencyMs: 95,
    status: 'ACTIVE',
  },
  {
    id: 'cap_ace_lego',
    capability: 'realization.instrument.contextual (ACE lego)',
    category: 'ACE-Step 1.5 XL Base',
    description: 'Generates an accompaniment instrument track (e.g. Bass, Pad) perfectly locked to existing context stems.',
    currentProvider: 'ACE-Step 1.5 XL Base (lego)',
    availableProviders: ['ACE-Step 1.5 XL Base (lego)', 'SoulSonus Session Player Core'],
    codeLicense: 'Apache-2.0',
    checkpointLicense: 'OpenRAIL-M',
    commercialStatus: 'COMMERCIAL_OK',
    modelHash: 'sha256_ace15_xl_lego_33d2',
    soulsonusLogic: 'Session Player persona directives (Marcus Miller gospel groove rules, frequency carving).',
    ossEngine: 'ACE-Step conditioned stem generator (bypasses generic LM for bounded multi-track context)',
    adapterContract: 'ContextStems + TargetRole + LengthBars -> StemAudio (Duration matched to source)',
    latencyMs: 110,
    status: 'ACTIVE',
  },
  {
    id: 'cap_ace_repaint',
    capability: 'transformation.region.repaint (ACE repaint)',
    category: 'ACE-Step 1.5 XL Base',
    description: 'Inpaints or restyles an exact bounded time region (e.g. Bars 13-20) leaving surrounding music pristine.',
    currentProvider: 'ACE-Step 1.5 XL Base (repaint)',
    availableProviders: ['ACE-Step 1.5 XL Base (repaint)', 'Native DAW Crossfade Inpainter'],
    codeLicense: 'Apache-2.0',
    checkpointLicense: 'OpenRAIL-M',
    commercialStatus: 'COMMERCIAL_OK',
    modelHash: 'sha256_ace15_xl_repaint_7a1',
    soulsonusLogic: 'ChangeSet safety contract: guarantees unselected bars remain bit-for-bit identical.',
    ossEngine: 'ACE-Step masked diffusion inpainting',
    adapterContract: 'SourceTrack + [StartBar, EndBar] + Mask + Direction -> PatchedAudioBuffer',
    latencyMs: 80,
    status: 'ACTIVE',
  },
  {
    id: 'cap_ace_complete',
    capability: 'realization.arrangement.complete (ACE complete)',
    category: 'ACE-Step 1.5 XL Base',
    description: 'Fills out sparse arrangements into rich multi-instrument productions according to creator vision.',
    currentProvider: 'ACE-Step 1.5 XL Base (complete)',
    availableProviders: ['ACE-Step 1.5 XL Base (complete)', 'The Band Session Ensemble'],
    codeLicense: 'Apache-2.0',
    checkpointLicense: 'OpenRAIL-M',
    commercialStatus: 'COMMERCIAL_OK',
    modelHash: 'sha256_ace15_xl_compl_88e0',
    soulsonusLogic: 'Preserves vocal and lead melodic identity while structuring rhythm and harmonic layers.',
    ossEngine: 'ACE-Step multi-instrument completion model',
    adapterContract: 'SparseMix + SectionRoadmap -> MultiStemPackage',
    latencyMs: 140,
    status: 'READY',
  },
  {
    id: 'cap_ace_extract',
    capability: 'separation.semantic.extract (ACE extract)',
    category: 'ACE-Step 1.5 XL Base',
    description: 'Extracts requested musical role or instrument from combined arrangement.',
    currentProvider: 'ACE-Step 1.5 XL Base (extract)',
    availableProviders: ['ACE-Step 1.5 XL Base (extract)', 'Demucs v4 Hybrid'],
    codeLicense: 'Apache-2.0',
    checkpointLicense: 'OpenRAIL-M',
    commercialStatus: 'COMMERCIAL_OK',
    modelHash: 'sha256_ace15_xl_extr_55c1',
    soulsonusLogic: 'Lineage tracking and SeedSignature provenance stamping on extracted assets.',
    ossEngine: 'ACE-Step semantic conditioned extraction',
    adapterContract: 'AudioMix + TargetStemName -> IsolatedStemBuffer',
    latencyMs: 90,
    status: 'ACTIVE',
  },
  {
    id: 'cap_ace_cover',
    capability: 'transformation.reference.cover (ACE cover)',
    category: 'ACE-Step 1.5 XL Base',
    description: 'Re-arranges a reference audio recording into a new production style while keeping core harmony and melody.',
    currentProvider: 'ACE-Step 1.5 XL Base (cover)',
    availableProviders: ['ACE-Step 1.5 XL Base (cover)', 'SoulSonus Style Transformer'],
    codeLicense: 'Apache-2.0',
    checkpointLicense: 'OpenRAIL-M',
    commercialStatus: 'COMMERCIAL_OK',
    modelHash: 'sha256_ace15_xl_cvr_192e',
    soulsonusLogic: 'Creator rights verification & preservation of original melodic hooks and vocal phrasing.',
    ossEngine: 'ACE-Step reference guided diffusion',
    adapterContract: 'ReferenceAudio + StylePrompt -> RenderedAudio (Exact length preserved)',
    latencyMs: 125,
    status: 'READY',
  },
  {
    id: 'cap_demucs',
    capability: 'Stem Separation (audio.stems.isolate)',
    category: 'Sourcing & Import',
    description: 'Isolates 4 or 6 discrete stems (vocals, drums, bass, other, piano, guitar) from imported audio.',
    currentProvider: 'Demucs v4 Hybrid (HTDemucs)',
    availableProviders: ['Demucs v4 Hybrid (HTDemucs)', 'Curated UVR Models', 'MDX-Net'],
    codeLicense: 'MIT',
    checkpointLicense: 'Creative Commons / Permissive',
    commercialStatus: 'COMMERCIAL_OK',
    modelHash: 'sha256_htdemucs_v4_81f2',
    soulsonusLogic: 'Stem tagging, phase alignment verification, and automated project routing.',
    ossEngine: 'Hybrid Transformer Demucs (Défossez et al.)',
    adapterContract: 'MixedFile (WAV/MP3) -> { vocals, drums, bass, other } AudioBuffers',
    latencyMs: 150,
    status: 'ACTIVE',
  },
  {
    id: 'cap_whisper',
    capability: 'Speech & Word Timing (vocal.lyrics.align)',
    category: 'Phonetic Intelligence',
    description: 'Transcribes spoken/sung vocals and provides forced phoneme & word level timestamp alignment.',
    currentProvider: 'WhisperX + Montreal Forced Aligner',
    availableProviders: ['WhisperX + Montreal Forced Aligner', 'faster-whisper', 'whisper.cpp'],
    codeLicense: 'BSD-3-Clause / MIT',
    checkpointLicense: 'MIT',
    commercialStatus: 'COMMERCIAL_OK',
    modelHash: 'sha256_wx_phon_9921',
    soulsonusLogic: 'Preserves scratch vocal vowel cadences and links syllables to DAW lyric markers.',
    ossEngine: 'faster-whisper CTC phoneme model + Wav2Vec2 forced aligner',
    adapterContract: 'VocalAudio -> WordTiming[] { word, startMs, endMs, phonemes[] }',
    latencyMs: 25,
    status: 'ACTIVE',
  },
  {
    id: 'cap_magenta_rt',
    capability: 'Interactive Musician Companion (session.player.live)',
    category: 'Session Player Brain',
    description: 'Real-time interactive session accompaniment responding dynamically to creator input.',
    currentProvider: 'Magenta RealTime 2 + SoulSonus Persona Engine',
    availableProviders: ['Magenta RealTime 2 + SoulSonus Persona Engine', 'SoulSonus Symbolic Accompanist'],
    codeLicense: 'Apache-2.0',
    checkpointLicense: 'Apache-2.0',
    commercialStatus: 'COMMERCIAL_OK',
    modelHash: 'sha256_magentart2_01ab',
    soulsonusLogic: 'Marcus Miller persona memory, gospel jazz vocabulary, long-horizon arrangement awareness.',
    ossEngine: 'Magenta RT2 low-latency transformer',
    adapterContract: 'LiveMidiStream / AudioStream -> RealTimeMidiEvents',
    latencyMs: 12,
    status: 'ACTIVE',
  },
  {
    id: 'cap_bgv_synth',
    capability: 'Choir & Vocal Synthesis (vocal.harmony.render)',
    category: 'BGV Gospel Studio',
    description: 'Synthesizes authentic multi-part background vocal harmonies using rights-cleared singer models.',
    currentProvider: 'DiffSinger / NNSVS (Licensed Voicebanks)',
    availableProviders: ['DiffSinger / NNSVS (Licensed Voicebanks)', 'SoulSonus Formant Choir Synth'],
    codeLicense: 'Apache-2.0 (DiffSinger code)',
    checkpointLicense: 'SoulSonus Rights-Cleared Voicebank',
    commercialStatus: 'RIGHTS_CONTROLLED',
    modelHash: 'sha256_diffsinger_rc_771b',
    soulsonusLogic: 'Gospel harmony director: open 3rds/5ths/flat 7ths, breath phrasing, formant blending.',
    ossEngine: 'DiffSinger acoustic model + HifiGAN vocoder',
    adapterContract: 'LeadVocalSMIR + HarmonyScores + Lyrics -> 3-Part Stems (SAT)',
    latencyMs: 130,
    status: 'ACTIVE',
  },
  {
    id: 'cap_master_lufs',
    capability: 'Loudness & True Peak Compliance (master.meter.ebur128)',
    category: 'Mastering & Delivery',
    description: 'Calculates ITU-R BS.1770-4 / EBU R128 integrated LUFS, loudness range (LRA), and true-peak dBFS.',
    currentProvider: 'libebur128 Native / pyloudnorm',
    availableProviders: ['libebur128 Native / pyloudnorm', 'Web Audio Loudness Node'],
    codeLicense: 'MIT',
    checkpointLicense: 'Pure DSP / No Weights',
    commercialStatus: 'PERMISSIVE',
    modelHash: 'dsp_libebur128_v1.2.6',
    soulsonusLogic: 'Validates target loudness for Streaming (-14 LUFS), Club (-9 LUFS), and Audiophile masters.',
    ossEngine: 'libebur128 K-weighted filter bank and true peak oversampler',
    adapterContract: 'MasterStereoBuffer -> { integratedLufs, lra, maxTruePeakDb, status }',
    latencyMs: 8,
    status: 'ACTIVE',
  },
];

export const INITIAL_PIPELINE_STAGES: PipelineStage[] = [
  { id: 'p1', label: 'Creator Request', sublabel: 'Natural Language or Audio Input', status: 'completed', detail: '“Marcus, stay out of the vocal.”' },
  { id: 'p2', label: 'Studio Intelligence', sublabel: 'Intent Classification & Context Parser', status: 'completed', detail: 'Target: Track 04 (Marcus), Context: Track 03 (Lead Vocal), Bars 13-20.' },
  { id: 'p3', label: 'SoulIntent / SMIR', sublabel: 'Source Musical Intent Representation', status: 'completed', detail: 'Rules: Duck 250-600Hz, preserve kick lock, maintain tempo +12ms.' },
  { id: 'p4', label: 'ChangeSet Formulator', sublabel: 'Boundary Specification & Safety Contract', status: 'active', detail: 'Scope bounded to Track 04. Prohibited changes locked.' },
  { id: 'p5', label: 'Orchestration Graph', sublabel: 'Directed Acyclic Execution Graph', status: 'waiting', detail: 'Nodes: [GrooveLock, FrequencyLaneCarver, TakeRenderer]' },
  { id: 'p6', label: 'Capability Resolver', sublabel: 'Service & Model Registry Lookup', status: 'waiting', detail: 'Resolved to: Composite SoulSonus Recipe with ACE-Step Adapter.' },
  { id: 'p7', label: 'Provider Adapter', sublabel: 'Parameter Normalizer & Bridge', status: 'waiting', detail: 'Maps SMIR constraints into ACE-Step generation conditioning.' },
  { id: 'p8', label: 'Open-Source / Native Engine', sublabel: 'Execution on Low-Latency Runtime', status: 'waiting', detail: 'Runs 8 bars of bass variation constrained by Marcus Persona.' },
  { id: 'p9', label: 'Normalization & Validation', sublabel: 'Verification against SMIR Rules', status: 'waiting', detail: 'Validates: frequency lane not violated, kick timing delta < 4ms.' },
  { id: 'p10', label: 'SoulTake Generation', sublabel: 'Containerized Audio/MIDI Artifact', status: 'waiting', detail: 'Emits Marcus · Bass · Take 4 with SeedSignature receipt.' },
  { id: 'p11', label: 'Unified DAW Integration', sublabel: 'Non-Destructive Project Tree Update', status: 'waiting', detail: 'Places alternate take on timeline, non-destructive comping ready.' },
];
